### ISSUE TITLE
rini_load_config's implementation is marked as static

### ISSUE THREAD

**Issue by ERmilburn02** [raysan5/rini#1]
In the implementation of [rini_load_config](https://github.com/raysan5/rini/blob/ef31a3d4c8f22a5875b3bc409a6501bec8968646/src/rini.h#L259), the function is marked as static. This is preventing it from being used in files other than the one that the implementation is defined in. I believe this is a bug, as the rest of the module's functions are not marked as static, allowing them to be used anywhere.

The issue didn't seem to appear when using C and clang, but it did show up when the rest of the project was C++, and using MSVC, but the issue seems to occur with both C and C++.

I've attached a [Reproducible Example](https://github.com/raysan5/rini/files/11568322/example.zip) to allow you to see the issue.

Environment: Windows 11 22H2 (10.0.22621.1702)
Compiler: MSVC (Microsoft Visual C++) version 19.35.32215
Commit: ef31a3d

**Comment by raysan5** [comment]
@ERmilburn02 Hey! First issue found! Good catch! :D

**Comment by raysan5** [comment]
Fixed!
