### ISSUE TITLE
value delimiter

### ISSUE THREAD

**Issue by seropigeorgedev** [raysan5/rini#2]
I think I am doing something wrong but idk, the value delimiter looks hard coded to a ' ' even if u change it to a '=' it won't work and a space will .ini files should work like this as well:KEY=7 ; but rini doesn't so I changed the ' ' to the value delimiter macro and then it does work ig
https://github.com/raysan5/rini/blob/main/src/rini.h#L496 here is the issue start

**Comment by seropigeorgedev** [comment]
ye no replacing it by the macro won't fully fix it just the way I want it but not anymore with a "key = 8" which also should work with .ini files

**Comment by seropigeorgedev** [comment]
no it's just the '  ' thing always being accepted despite the macro being changed so that is the real issue ig

**Comment by raysan5** [comment]
@seropigeorgedev I checked the code and it looks ok to me, `" "` is always skipped, despite the defined delimiter.

**Comment by seropigeorgedev** [comment]
> @seropigeorgedev I checked the code and it looks ok to me, `" "` is always skipped, despite the defined delimiter.

Idk me and another cool programmer tried this first time never really worked with .ini files but from what I have seen it should be possible to set the delimiter to anything u want and not needing and always accepting a space as a delimiter so for example here with rini when u change the delimiter to = it will still accept a space and when u have "key=7" for example it will not work only when there is a space with it or just a space which is not how it's supposed to work at least from what I have seen

**Comment by raysan5** [comment]
@seropigeorgedev As per the [INI file information on Wikipedia](https://en.wikipedia.org/wiki/INI_file) I assumed that key-value pair delimiters were always surrounded by spaces (all examples I saw followed that approach). I can review that.

But please note that `rini` is not compliant with "standard" ini files, actually there are no "standard" ini files, every developer uses its own approaches. For example `rini` does not support `sections` by design.

**Comment by seropigeorgedev** [comment]
Okay thanks for the information we weren't really familiar with ini file and looked at some examples and thought that there was a default thing but never mind, there is still one question that I have should space by itself always count and work as a delimiter even though the macro has been changed?

**Comment by raysan5** [comment]
> should space by itself always count and work as a delimiter even though the macro has been changed?

@seropigeorgedev Not really, it depends on the implementation and the developers (i.e. keys with spaces).. There is no solution that fit all use cases, there are always some constraints. Probably that specifc `rini` constraint should be added to the header info to warn developers about it, it already has a "limitations" section.

**Comment by seropigeorgedev** [comment]
Idk but it does look like a bug to me, however I do have one last question: why are there no [sections]?

**Comment by raysan5** [comment]
@seropigeorgedev because I didn't need it for my use cases and implementing it required an extra cost that I didn't want to assume.
