### ISSUE TITLE
const fix C++

### ISSUE THREAD

**Issue by tyqualters** [raysan5/rini#3]
To get rini.h to work for me in C++ I had to change line 498 `char *buffer_ptr = buffer;` to `const char *buffer_ptr = buffer;` to fix error:

> .../rini-main/src/rini.h:498:24: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
>   498 |     char *buffer_ptr = buffer;

**Comment by raysan5** [comment]
@tyqualters Thanks for reporting! Feel free to send a PR with the review.

**Comment by tyqualters** [comment]
> @tyqualters Thanks for reporting! Feel free to send a PR with the review.

Ok, I created a Pull Request with the change
